window.app_vars = {
	app_state: {
		VERSION: 99999,
		MCU: 'MCU_AVR',
		KINEMATIC: 'KINEMATIC_CARTESIAN',
		BAUDRATE: 115200
	},
	app_fields: {
		VERSION: { type: 'int', nullable: false, file: '' },
		MCU: { type: '', nullable: false, file: 'boardmap' },
		KINEMATIC: { type: '', nullable: false, file: 'hal' },
		BAUDRATE: { type: 'int', nullable: false, file: 'boardmap' },
	},
	app_options: {
		VERSIONS: [
			{ id: 'master', tag: 99999, src: 'https://github.com/Paciente8159/uCNC/archive/refs/heads/master.zip', mods: 'https://github.com/Paciente8159/uCNC-modules/archive/refs/heads/master.zip' },
			{ id: 'v1.13.0', tag: 11300, src: 'https://github.com/Paciente8159/uCNC/archive/refs/tags/v1.13.0.zip', mods: 'https://github.com/Paciente8159/uCNC-modules/archive/refs/heads/master.zip' },
			{ id: 'v1.13.rc', tag: 11290, src: 'https://github.com/Paciente8159/uCNC/archive/refs/tags/v1.13.rc.zip', mods: 'https://github.com/Paciente8159/uCNC-modules/archive/refs/heads/master.zip' },
			{ id: 'v1.12.4', tag: 11204, src: 'https://github.com/Paciente8159/uCNC/archive/refs/tags/v1.12.4.zip', mods: 'https://github.com/Paciente8159/uCNC-modules/archive/refs/heads/master.zip' },
			{ id: 'v1.12.3', tag: 11203, src: 'https://github.com/Paciente8159/uCNC/archive/refs/tags/v1.12.3.zip', mods: 'https://github.com/Paciente8159/uCNC-modules/archive/refs/heads/master.zip' },
			{ id: 'v1.12.2', tag: 11202, src: 'https://github.com/Paciente8159/uCNC/archive/refs/tags/v1.12.2.zip', mods: 'https://github.com/Paciente8159/uCNC-modules/archive/refs/heads/master.zip' },
			{ id: 'v1.12.1', tag: 11201, src: 'https://github.com/Paciente8159/uCNC/archive/refs/tags/v1.12.1.zip', mods: 'https://github.com/Paciente8159/uCNC-modules/archive/refs/heads/master.zip' },
			{ id: 'v1.12.0', tag: 11200, src: 'https://github.com/Paciente8159/uCNC/archive/refs/tags/v1.12.0.zip', mods: 'https://github.com/Paciente8159/uCNC-modules/archive/refs/heads/master.zip' },
		],
		BAUDRATES: [
			{ id: 9600 },
			{ id: 19200 },
			{ id: 38400 },
			{ id: 57600 },
			{ id: 115200 },
			{ id: 230400 },
			{ id: 250000 },
			{ id: 576000 }
		],
		MCUS: [
			{ id: 'MCU_AVR', name: 'Atmel AVR', url: 'src/hal/mcus/avr/mcumap_avr.h' },
			{ id: 'MCU_SAMD21', name: 'Atmel SAMD21', url: 'src/hal/mcus/samd21/mcumap_samd21.h' },
			{ id: 'MCU_STM32F0X', name: 'STM32F0x', url: 'src/hal/mcus/stm32f0x/mcumap_stm32f0x.h' },
			{ id: 'MCU_STM32F1X', name: 'STM32F1x', url: 'src/hal/mcus/stm32f1x/mcumap_stm32f1x.h' },
			{ id: 'MCU_STM32F4X', name: 'STM32F4X', url: 'src/hal/mcus/stm32f4x/mcumap_stm32f4x.h' },
			{ id: 'MCU_STM32H7X', name: 'STM32H7X', url: 'src/hal/mcus/stm32h7x/mcumap_stm32h7x.h' },
			{ id: 'MCU_LPC176X', name: 'LPC176X', url: 'src/hal/mcus/lpc176x/mcumap_lpc176x.h' },
			{ id: 'MCU_ESP8266', name: 'ESP8266', url: 'src/hal/mcus/esp8266/mcumap_esp8266.h' },
			{ id: 'MCU_ESP32', name: 'ESP32', url: 'src/hal/mcus/esp32/mcumap_esp32.h' },
			{ id: 'MCU_ESP32C3', name: 'ESP32C3', url: 'src/hal/mcus/esp32c3/mcumap_esp32c3.h' },
			{ id: 'MCU_ESP32S3', name: 'ESP32S3', url: 'src/hal/mcus/esp32s3/mcumap_esp32s3.h' },
			{ id: 'MCU_RP2040', name: 'RPi RP2040', url: 'src/hal/mcus/rp2040/mcumap_rp2040.h' },
			{ id: 'MCU_RP2350', name: 'RPi RP2350', url: 'src/hal/mcus/rp2350/mcumap_rp2350.h' }
		],
		KINEMATICS: [
			{ id: 'KINEMATIC_CARTESIAN', name: 'Cartesian', version: 0 },
			{ id: 'KINEMATIC_COREXY', name: 'Core XY', version: 0 },
			{ id: 'KINEMATIC_LINEAR_DELTA', name: 'Linear delta', version: 0 },
			{ id: 'KINEMATIC_DELTA', name: 'Delta robot', version: 0 },
			{ id: 'KINEMATIC_SCARA', name: 'Scara', version: 10799 },
			{ id: 'KINEMATIC_RTHETA', name: 'RTheta', version: 11200 }
		],
		ACCELERATIONS: [
			{ id: -1, name: 'Selectable via $14' },
			{ id: 0, name: 'Disabled (linear)' },
			{ id: 1, name: 'Soft' },
			{ id: 2, name: 'Mild' },
			{ id: 3, name: 'Hard' },
			{ id: 4, name: 'Aggressive' },
			{ id: 5, name: 'Aggressive2' }
		],
		S_CURVE_ACCELERATION_LEVEL: 0,

		BOARDS: [
			{ id: 'src/hal/boards/avr/boardmap_uno.h', name: 'Arduino UNO', mcu: 'MCU_AVR' },
			{ id: 'src/hal/boards/avr/boardmap_rambo14.h', name: 'Rambo v1.4', mcu: 'MCU_AVR' },
			{ id: 'src/hal/boards/avr/boardmap_ramps14.h', name: 'Arduino MEGA/RAMPS v1.4', mcu: 'MCU_AVR' },
			{ id: 'src/hal/boards/avr/boardmap_mks_dlc.h', name: 'MKS DLC', mcu: 'MCU_AVR' },
			{ id: 'src/hal/boards/avr/boardmap_x_controller.h', name: 'X-Controller', mcu: 'MCU_AVR' },
			{ id: 'src/hal/boards/avr/boardmap_uno_shield_v3.h', name: 'Arduino UNO Shield v3', mcu: 'MCU_AVR' },
			{ id: 'src/hal/boards/avr/boardmap_mks_gen_l_v1.h', name: 'MKS Gen L v1', mcu: 'MCU_AVR' },
			{ id: 'src/hal/boards/avr/boardmap_melzi_v114.h', name: 'Melzi v1.1.4', mcu: 'MCU_AVR' },
			{ id: 'src/hal/boards/avr/boardmap_mega_shield_v3.h', name: 'Arduino MEGA Shield V3', mcu: 'MCU_AVR' },
			{ id: 'src/hal/boards/stm32/boardmap_bluepill_f0.h', name: 'Bluepill STM32F030', mcu: 'MCU_STM32F0X' },
			{ id: 'src/hal/boards/stm32/boardmap_bluepill.h', name: 'Bluepill STM32F103', mcu: 'MCU_STM32F1X' },
			{ id: 'src/hal/boards/stm32/boardmap_blackpill.h', name: 'Blackpill STM32F401', mcu: 'MCU_STM32F4X' },
			{ id: 'src/hal/boards/stm32/boardmap_mks_robin_nano_v1_2.h', name: 'MKS Robin Nano v1.2', mcu: 'MCU_STM32F1X' },
			{ id: 'src/hal/boards/stm32/boardmap_mks_robin_nano_v3_1.h', name: 'MKS Robin Nano v3.1', mcu: 'MCU_STM32F4X' },
			{ id: 'src/hal/boards/stm32/boardmap_srk_pro_v1_2.h', name: 'SKR Pro v1.2', mcu: 'MCU_STM32F4X' },
			{ id: 'src/hal/boards/stm32/boardmap_nucleo_f411re_shield_v3.h', name: 'STM32 Nucleo F411RE', mcu: 'MCU_STM32F4X' },
			{ id: 'src/hal/boards/stm32/boardmap_generic_h750.h', name: 'WeAct STM32H750 Mini', mcu: 'MCU_STM32H7X' },
			{ id: 'src/hal/boards/stm32/boardmap_skr3.h', name: 'BTT SKR3', mcu: 'MCU_STM32H7X' },
			{ id: 'src/hal/boards/samd21/boardmap_mzero.h', name: 'Arduino M0', mcu: 'MCU_SAMD21' },
			{ id: 'src/hal/boards/samd21/boardmap_zero.h', name: 'Arduino Zero', mcu: 'MCU_SAMD21' },
			{ id: 'src/hal/boards/lpc176x/boardmap_re_arm.h', name: 'Panukatt RE-ARM', mcu: 'MCU_LPC176X' },
			{ id: 'src/hal/boards/lpc176x/boardmap_mks_base13.h', name: 'MKS Base v1.3', mcu: 'MCU_LPC176X' },
			{ id: 'src/hal/boards/lpc176x/boardmap_skr_v14_turbo.h', name: 'SKR v1.4 Turbo', mcu: 'MCU_LPC176X' },
			{ id: 'src/hal/boards/esp8266/boardmap_wemos_d1.h', name: 'Wemos D1', mcu: 'MCU_ESP8266' },
			{ id: 'src/hal/boards/esp32/boardmap_wemos_d1_r32.h', name: 'Wemos D1 R32', mcu: 'MCU_ESP32' },
			{ id: 'src/hal/boards/esp32/boardmap_mks_tinybee.h', name: 'MKS Tinybee', mcu: 'MCU_ESP32' },
			{ id: 'src/hal/boards/esp32/boardmap_mks_dlc32.h', name: 'MKS DLC32', mcu: 'MCU_ESP32' },
			{ id: 'src/hal/boards/esp32/boardmap_core_c3.h', name: 'CORE ESP32 S3', mcu: 'MCU_ESP32C3' },
			{ id: 'src/hal/boards/esp32/boardmap_devkit_s3.h', name: 'Devkit S3', mcu: 'MCU_ESP32S3' },
			{ id: 'src/hal/boards/rp2040/boardmap_rpi_pico.h', name: 'RPi Pico', mcu: 'MCU_RP2040' },
			{ id: 'src/hal/boards/rp2040/boardmap_rpi_pico_w.h', name: 'RPi Pico W', mcu: 'MCU_RP2040' },
			{ id: 'src/hal/boards/rp2350/boardmap_rpi_pico2.h', name: 'RPi Pico 2', mcu: 'MCU_RP2350' },
			{ id: 'boardmap_overrides.h', name: 'Custom board', mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32C3,MCU_ESP32S3,MCU_RP2040,MCU_RP2350' }
		],
		UCNCPINS: [
			{ pin: 'STEP0', type: 'stepper,special_output' },
			{ pin: 'STEP1', type: 'stepper,special_output' },
			{ pin: 'STEP2', type: 'stepper,special_output' },
			{ pin: 'STEP3', type: 'stepper,special_output' },
			{ pin: 'STEP4', type: 'stepper,special_output' },
			{ pin: 'STEP5', type: 'stepper,special_output' },
			{ pin: 'STEP6', type: 'stepper,special_output' },
			{ pin: 'STEP7', type: 'stepper,special_output' },
			{ pin: 'DIR0', type: 'stepper,special_output' },
			{ pin: 'DIR1', type: 'stepper,special_output' },
			{ pin: 'DIR2', type: 'stepper,special_output' },
			{ pin: 'DIR3', type: 'stepper,special_output' },
			{ pin: 'DIR4', type: 'stepper,special_output' },
			{ pin: 'DIR5', type: 'stepper,special_output' },
			{ pin: 'DIR6', type: 'stepper,special_output' },
			{ pin: 'DIR7', type: 'stepper,special_output' },
			{ pin: 'STEP0_EN', type: 'stepper,special_output' },
			{ pin: 'STEP1_EN', type: 'stepper,special_output' },
			{ pin: 'STEP2_EN', type: 'stepper,special_output' },
			{ pin: 'STEP3_EN', type: 'stepper,special_output' },
			{ pin: 'STEP4_EN', type: 'stepper,special_output' },
			{ pin: 'STEP5_EN', type: 'stepper,special_output' },
			{ pin: 'STEP6_EN', type: 'stepper,special_output' },
			{ pin: 'STEP7_EN', type: 'stepper,special_output' },
			{ pin: 'PWM0', type: 'pwm' },
			{ pin: 'PWM1', type: 'pwm' },
			{ pin: 'PWM2', type: 'pwm' },
			{ pin: 'PWM3', type: 'pwm' },
			{ pin: 'PWM4', type: 'pwm' },
			{ pin: 'PWM5', type: 'pwm' },
			{ pin: 'PWM6', type: 'pwm' },
			{ pin: 'PWM7', type: 'pwm' },
			{ pin: 'PWM8', type: 'pwm' },
			{ pin: 'PWM9', type: 'pwm' },
			{ pin: 'PWM10', type: 'pwm' },
			{ pin: 'PWM11', type: 'pwm' },
			{ pin: 'PWM12', type: 'pwm' },
			{ pin: 'PWM13', type: 'pwm' },
			{ pin: 'PWM14', type: 'pwm' },
			{ pin: 'PWM15', type: 'pwm' },
			{ pin: 'SERVO0', type: 'servo' },
			{ pin: 'SERVO1', type: 'servo' },
			{ pin: 'SERVO2', type: 'servo' },
			{ pin: 'SERVO3', type: 'servo' },
			{ pin: 'SERVO4', type: 'servo' },
			{ pin: 'SERVO5', type: 'servo' },
			{ pin: 'DOUT0', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT1', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT2', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT3', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT4', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT5', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT6', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT7', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT8', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT9', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT10', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT11', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT12', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT13', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT14', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT15', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT16', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT17', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT18', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT19', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT20', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT21', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT22', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT23', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT24', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT25', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT26', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT27', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT28', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT29', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT30', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT31', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT32', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT33', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT34', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT35', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT36', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT37', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT38', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT39', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT40', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT41', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT42', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT43', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT44', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT45', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT46', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT47', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT48', type: 'dout,generic_output,generic_io' },
			{ pin: 'DOUT49', type: 'dout,generic_output,generic_io' },
			{ pin: 'LIMIT_X', type: 'limit,interruptable_input,pullup' },
			{ pin: 'LIMIT_Y', type: 'limit,interruptable_input,pullup' },
			{ pin: 'LIMIT_Z', type: 'limit,interruptable_input,pullup' },
			{ pin: 'LIMIT_X2', type: 'limit,interruptable_input,pullup' },
			{ pin: 'LIMIT_Y2', type: 'limit,interruptable_input,pullup' },
			{ pin: 'LIMIT_Z2', type: 'limit,interruptable_input,pullup' },
			{ pin: 'LIMIT_A', type: 'limit,interruptable_input,pullup' },
			{ pin: 'LIMIT_B', type: 'limit,interruptable_input,pullup' },
			{ pin: 'LIMIT_C', type: 'limit,interruptable_input,pullup' },
			{ pin: 'PROBE', type: 'probe,interruptable_input,pullup' },
			{ pin: 'ESTOP', type: 'control,interruptable_input,pullup' },
			{ pin: 'SAFETY_DOOR', type: 'control,interruptable_input,pullup' },
			{ pin: 'FHOLD', type: 'control,interruptable_input,pullup' },
			{ pin: 'CS_RES', type: 'control,interruptable_input,pullup' },
			{ pin: 'ANALOG0', type: 'analog' },
			{ pin: 'ANALOG1', type: 'analog' },
			{ pin: 'ANALOG2', type: 'analog' },
			{ pin: 'ANALOG3', type: 'analog' },
			{ pin: 'ANALOG4', type: 'analog' },
			{ pin: 'ANALOG5', type: 'analog' },
			{ pin: 'ANALOG6', type: 'analog' },
			{ pin: 'ANALOG7', type: 'analog' },
			{ pin: 'ANALOG8', type: 'analog' },
			{ pin: 'ANALOG9', type: 'analog' },
			{ pin: 'ANALOG10', type: 'analog' },
			{ pin: 'ANALOG11', type: 'analog' },
			{ pin: 'ANALOG12', type: 'analog' },
			{ pin: 'ANALOG13', type: 'analog' },
			{ pin: 'ANALOG14', type: 'analog' },
			{ pin: 'ANALOG15', type: 'analog' },
			{ pin: 'DIN0', type: 'din,interruptable_generic_input,generic_io,interruptable_input,generic_input,pullup,unsafe_generic_input' },
			{ pin: 'DIN1', type: 'din,interruptable_generic_input,generic_io,interruptable_input,generic_input,pullup,unsafe_generic_input' },
			{ pin: 'DIN2', type: 'din,interruptable_generic_input,generic_io,interruptable_input,generic_input,pullup,unsafe_generic_input' },
			{ pin: 'DIN3', type: 'din,interruptable_generic_input,generic_io,interruptable_input,generic_input,pullup,unsafe_generic_input' },
			{ pin: 'DIN4', type: 'din,interruptable_generic_input,generic_io,interruptable_input,generic_input,pullup,unsafe_generic_input' },
			{ pin: 'DIN5', type: 'din,interruptable_generic_input,generic_io,interruptable_input,generic_input,pullup,unsafe_generic_input' },
			{ pin: 'DIN6', type: 'din,interruptable_generic_input,generic_io,interruptable_input,generic_input,pullup,unsafe_generic_input' },
			{ pin: 'DIN7', type: 'din,interruptable_generic_input,generic_io,interruptable_input,generic_input,pullup,unsafe_generic_input' },
			{ pin: 'DIN8', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN9', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN10', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN11', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN12', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN13', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN14', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN15', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN16', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN17', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN18', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN19', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN20', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN21', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN22', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN23', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN24', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN25', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN26', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN27', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN28', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN29', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN30', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN31', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN32', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN33', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN34', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN35', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN36', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN37', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN38', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN39', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN40', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN41', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN42', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN43', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN44', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN45', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN46', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN47', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN48', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'DIN49', type: 'din,generic_input,generic_io,pullup,unsafe_generic_input' },
			{ pin: 'TX', type: 'communications,special_output' },
			{ pin: 'RX', type: 'communications,special input' },
			{ pin: 'USB_DM', type: 'communications,special_output' },
			{ pin: 'USB_DP', type: 'communications,special_output' },
			{ pin: 'SPI_CLK', type: 'communications,special_output' },
			{ pin: 'SPI_SDI', type: 'communications,special input' },
			{ pin: 'SPI_SDO', type: 'communications,special_output' },
			{ pin: 'SPI_CS', type: 'communications,special_output,generic_output' },
			{ pin: 'I2C_CLK', type: 'communications,special input' },
			{ pin: 'I2C_DATA', type: 'communications,special input' },
			{ pin: 'TX2', type: 'communications,special input' },
			{ pin: 'RX2', type: 'communications,special input' },
			{ pin: 'SPI2_CLK', type: 'communications,special_output' },
			{ pin: 'SPI2_SDI', type: 'communications,special input' },
			{ pin: 'SPI2_SDO', type: 'communications,special_output' },
			{ pin: 'SPI2_CS', type: 'communications,special_output,generic_output' },
		],
		PINS: [
			{ pin: 0, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_ESP32C3,MCU_RP2040,MCU_RP2350' },
			{ pin: 1, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_ESP32C3,MCU_RP2040,MCU_RP2350' },
			{ pin: 2, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_ESP32C3,MCU_RP2040,MCU_RP2350' },
			{ pin: 3, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_ESP32C3,MCU_RP2040,MCU_RP2350' },
			{ pin: 4, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_ESP32C3,MCU_RP2040,MCU_RP2350' },
			{ pin: 5, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_ESP32C3,MCU_RP2040,MCU_RP2350' },
			{ pin: 6, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_ESP32C3,MCU_RP2040,MCU_RP2350' },
			{ pin: 7, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_ESP32C3,MCU_RP2040,MCU_RP2350' },
			{ pin: 8, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_ESP32C3,MCU_RP2040,MCU_RP2350' },
			{ pin: 9, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_ESP32C3,MCU_RP2040,MCU_RP2350' },
			{ pin: 10, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_ESP32C3,MCU_RP2040,MCU_RP2350' },
			{ pin: 11, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_ESP32C3,MCU_RP2040,MCU_RP2350' },
			{ pin: 12, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_ESP32C3,MCU_RP2040,MCU_RP2350' },
			{ pin: 13, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_ESP32C3,MCU_RP2040,MCU_RP2350' },
			{ pin: 14, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_ESP32C3,MCU_RP2040,MCU_RP2350' },
			{ pin: 15, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_ESP32C3,MCU_RP2040,MCU_RP2350' },
			{ pin: 16, mcu: 'MCU_SAMD21,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_ESP32C3,MCU_RP2040,MCU_RP2350' },
			{ pin: 17, mcu: 'MCU_SAMD21,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_ESP32C3,MCU_RP2040,MCU_RP2350' },
			{ pin: 18, mcu: 'MCU_SAMD21,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_ESP32C3,MCU_RP2040,MCU_RP2350' },
			{ pin: 19, mcu: 'MCU_SAMD21,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_ESP32C3,MCU_RP2040,MCU_RP2350' },
			{ pin: 20, mcu: 'MCU_SAMD21,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_ESP32C3,MCU_RP2040,MCU_RP2350' },
			{ pin: 21, mcu: 'MCU_SAMD21,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_ESP32C3,MCU_RP2040,MCU_RP2350' },
			{ pin: 22, mcu: 'MCU_SAMD21,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_ESP32C3,MCU_RP2040,MCU_RP2350' },
			{ pin: 23, mcu: 'MCU_SAMD21,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_RP2040,MCU_RP2350' },
			{ pin: 24, mcu: 'MCU_SAMD21,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_RP2040,MCU_RP2350' },
			{ pin: 25, mcu: 'MCU_SAMD21,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_RP2040,MCU_RP2350' },
			{ pin: 26, mcu: 'MCU_SAMD21,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_RP2040,MCU_RP2350' },
			{ pin: 27, mcu: 'MCU_SAMD21,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_RP2040,MCU_RP2350' },
			{ pin: 28, mcu: 'MCU_SAMD21,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_RP2040,MCU_RP2350' },
			{ pin: 29, mcu: 'MCU_SAMD21,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3,MCU_RP2040,MCU_RP2350' },
			{ pin: 30, mcu: 'MCU_SAMD21,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3' },
			{ pin: 31, mcu: 'MCU_SAMD21,MCU_LPC176X,MCU_ESP8266,MCU_ESP32,MCU_ESP32S3' },
			{ pin: 32, mcu: 'MCU_ESP32,MCU_ESP32S3' },
			{ pin: 33, mcu: 'MCU_ESP32,MCU_ESP32S3' },
			{ pin: 34, mcu: 'MCU_ESP32,MCU_ESP32S3' },
			{ pin: 35, mcu: 'MCU_ESP32,MCU_ESP32S3' },
			{ pin: 36, mcu: 'MCU_ESP32,MCU_ESP32S3' },
			{ pin: 37, mcu: 'MCU_ESP32,MCU_ESP32S3' },
			{ pin: 38, mcu: 'MCU_ESP32,MCU_ESP32S3' },
			{ pin: 39, mcu: 'MCU_ESP32,MCU_ESP32S3' },
			{ pin: 40, mcu: 'MCU_ESP32,MCU_ESP32S3' },
			{ pin: 41, mcu: 'MCU_ESP32,MCU_ESP32S3' },
			{ pin: 42, mcu: 'MCU_ESP32,MCU_ESP32S3' },
			{ pin: 43, mcu: 'MCU_ESP32,MCU_ESP32S3' },
			{ pin: 44, mcu: 'MCU_ESP32,MCU_ESP32S3' },
			{ pin: 45, mcu: 'MCU_ESP32,MCU_ESP32S3' },
			{ pin: 46, mcu: 'MCU_ESP32' },
			{ pin: 47, mcu: 'MCU_ESP32' }
		],
		PORTS: [
			{ port: 'A', mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ port: 'B', mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ port: 'C', mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ port: 'D', mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ port: 'E', mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ port: 'F', mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ port: 'G', mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ port: 'H', mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ port: 'I', mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ port: 'J', mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ port: 'K', mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ port: 'L', mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ port: 'M', mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ port: 'N', mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ port: '0', mcu: 'MCU_LPC176X' },
			{ port: '1', mcu: 'MCU_LPC176X' },
			{ port: '2', mcu: 'MCU_LPC176X' },
			{ port: '3', mcu: 'MCU_LPC176X' },
			{ port: '4', mcu: 'MCU_LPC176X' }
		],
		ISRS: [
			{ isr: 0, mcu: 'MCU_AVR' },
			{ isr: 1, mcu: 'MCU_AVR' },
			{ isr: 2, mcu: 'MCU_AVR' },
			{ isr: -1, mcu: 'MCU_AVR' },
			{ isr: -2, mcu: 'MCU_AVR' },
			{ isr: -3, mcu: 'MCU_AVR' },
			{ isr: -4, mcu: 'MCU_AVR' },
			{ isr: -5, mcu: 'MCU_AVR' },
			{ isr: -6, mcu: 'MCU_AVR' },
			{ isr: -7, mcu: 'MCU_AVR' },
			{ isr: -8, mcu: 'MCU_AVR' }
		],
		CHANNELS: [
			{ channel: 0, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP32,MCU_ESP32,MCU_ESP32S3' },
			{ channel: 1, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP32,MCU_ESP32,MCU_ESP32S3' },
			{ channel: 2, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP32,MCU_ESP32,MCU_ESP32S3' },
			{ channel: 3, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP32,MCU_ESP32,MCU_ESP32S3' },
			{ channel: 4, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 5, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 6, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 7, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 8, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 9, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 10, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 11, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 12, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 13, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 14, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 15, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 'A', mcu: 'MCU_AVR' },
			{ channel: 'B', mcu: 'MCU_AVR' },
			{ channel: 'C', mcu: 'MCU_AVR' },
			{ channel: 'D', mcu: 'MCU_AVR' }
		],
		ANALOG_CHANNELS: [
			{ channel: 0, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP32,MCU_ESP32,MCU_ESP32S3' },
			{ channel: 1, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP32,MCU_ESP32,MCU_ESP32S3' },
			{ channel: 2, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP32,MCU_ESP32,MCU_ESP32S3' },
			{ channel: 3, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP32,MCU_ESP32,MCU_ESP32S3' },
			{ channel: 4, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 5, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 6, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 7, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 8, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 9, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 10, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 11, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 12, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 13, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 14, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 15, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ channel: 16, mcu: 'MCU_STM32H7X' },
			{ channel: 17, mcu: 'MCU_STM32H7X' },
			{ channel: 18, mcu: 'MCU_STM32H7X' },
			{ channel: 19, mcu: 'MCU_STM32H7X' }
		],
		ANALOG_ADCS: [
			{ adc: 1, mcu: 'MCU_STM32H7X' },
			{ adc: 2, mcu: 'MCU_STM32H7X' },
			{ adc: 3, mcu: 'MCU_STM32H7X' }
		],
		TIMERS: [
			{ timer: 0, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_RP2040,MCU_RP2350,MCU_ESP32,MCU_ESP32,MCU_ESP32S3' },
			{ timer: 1, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_RP2040,MCU_RP2350,MCU_ESP32,MCU_ESP32,MCU_ESP32S3' },
			{ timer: 2, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_RP2040,MCU_RP2350,MCU_ESP32,MCU_ESP32,MCU_ESP32S3' },
			{ timer: 3, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_RP2040,MCU_RP2350,MCU_ESP32,MCU_ESP32,MCU_ESP32S3' },
			{ timer: 4, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ timer: 5, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ timer: 6, mcu: 'MCU_SAMD21,MCU_STM32F0XMCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ timer: 7, mcu: 'MCU_SAMD21,MCU_STM32F0XMCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ timer: 8, mcu: 'MCU_SAMD21,MCU_STM32F0XMCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ timer: 9, mcu: 'MCU_SAMD21,MCU_STM32F0XMCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ timer: 10, mcu: 'MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ timer: 11, mcu: 'MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ timer: 12, mcu: 'MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ timer: 13, mcu: 'MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ timer: 14, mcu: 'MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ timer: 15, mcu: 'MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ timer: 16, mcu: 'MCU_STM32H7X' },
			{ timer: 17, mcu: 'MCU_STM32H7X' }
		],
		UCNCTIMERS: [
			{ timer: 'ITP', mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP32,MCU_ESP32,MCU_ESP32S3,MCU_RP2040,MCU_RP2350' },
			{ timer: 'RTC', mcu: 'MCU_AVR,MCU_RP2040,MCU_RP2350' },
			{ timer: 'SERVO', mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP32,MCU_ESP32,MCU_ESP32S3,MCU_RP2040,MCU_RP2350' },
			{ timer: 'ONESHOT', mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP32,MCU_ESP32,MCU_ESP32S3,MCU_RP2040,MCU_RP2350' }
		],
		UCNCUARTS: [
			{ port: 0, mcu: 'MCU_AVR,MCU_SAMD21,MCU_LPC176X,MCU_ESP32,MCU_RP2040,MCU_ESP8266,MCU_RP2350' },
			{ port: 1, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP32,MCU_ESP32,MCU_ESP32S3,MCU_RP2040,MCU_RP2350' },
			{ port: 2, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP32,MCU_ESP32,MCU_ESP32S3,MCU_RP2040,MCU_RP2350' },
			{ port: 3, mcu: 'MCU_AVR,MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X' },
			{ port: 4, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ port: 5, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' }
		],
		UCNCSPI: [
			{ port: 0, mcu: 'MCU_AVR,MCU_LPC176X,MCU_ESP32,MCU_ESP32,MCU_ESP32S3,MCU_RP2040,MCU_RP2350,MCU_ESP8266' },
			{ port: 1, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP32,MCU_ESP32,MCU_ESP32S3,MCU_RP2040,MCU_RP2350' },
			{ port: 2, mcu: 'MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_ESP32,MCU_ESP32,MCU_ESP32S3' },
			{ port: 3, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ port: 4, mcu: 'MCU_STM32H7X' },
			{ port: 5, mcu: 'MCU_STM32H7X' },
			{ port: 6, mcu: 'MCU_STM32H7X' }
		],
		UCNCI2C: [
			{ port: 0, mcu: 'MCU_AVR,MCU_SAMD21,MCU_LPC176X,MCU_ESP32,MCU_ESP32,MCU_ESP32S3,MCU_RP2040,MCU_RP2350' },
			{ port: 1, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP32,MCU_ESP32,MCU_ESP32S3,MCU_RP2040,MCU_RP2350' },
			{ port: 2, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X,MCU_LPC176X,MCU_ESP32,MCU_ESP32,MCU_ESP32S3' },
			{ port: 3, mcu: 'MCU_SAMD21,MCU_STM32F0X,MCU_STM32F1X,MCU_STM32F4X,MCU_STM32H7X' },
			{ port: 4, mcu: 'MCU_SAMD21,MCU_STM32H7X' },
			{ port: 5, mcu: 'MCU_SAMD21' }
		],
		IO_OFFSETS: [
			{ offset: 0, extcount: 0 },
			{ offset: 1, extcount: 0 },
			{ offset: 2, extcount: 0 },
			{ offset: 3, extcount: 0 },
			{ offset: 4, extcount: 0 },
			{ offset: 5, extcount: 0 },
			{ offset: 6, extcount: 0 },
			{ offset: 7, extcount: 0 },
			{ offset: 8, extcount: 1 },
			{ offset: 9, extcount: 1 },
			{ offset: 10, extcount: 1 },
			{ offset: 11, extcount: 1 },
			{ offset: 12, extcount: 1 },
			{ offset: 13, extcount: 1 },
			{ offset: 14, extcount: 1 },
			{ offset: 15, extcount: 1 },
			{ offset: 16, extcount: 2 },
			{ offset: 17, extcount: 2 },
			{ offset: 18, extcount: 2 },
			{ offset: 19, extcount: 2 },
			{ offset: 20, extcount: 2 },
			{ offset: 21, extcount: 2 },
			{ offset: 22, extcount: 2 },
			{ offset: 23, extcount: 2 },
			{ offset: 24, extcount: 3 },
			{ offset: 25, extcount: 3 },
			{ offset: 26, extcount: 3 },
			{ offset: 27, extcount: 3 },
			{ offset: 28, extcount: 3 },
			{ offset: 29, extcount: 3 },
			{ offset: 30, extcount: 3 },
			{ offset: 31, extcount: 3 },
			{ offset: 32, extcount: 4 },
			{ offset: 33, extcount: 4 },
			{ offset: 34, extcount: 4 },
			{ offset: 35, extcount: 4 },
			{ offset: 36, extcount: 4 },
			{ offset: 37, extcount: 4 },
			{ offset: 38, extcount: 4 },
			{ offset: 39, extcount: 4 },
			{ offset: 40, extcount: 5 },
			{ offset: 41, extcount: 5 },
			{ offset: 42, extcount: 5 },
			{ offset: 43, extcount: 5 },
			{ offset: 44, extcount: 5 },
			{ offset: 45, extcount: 5 },
			{ offset: 46, extcount: 5 },
			{ offset: 47, extcount: 5 },
			{ offset: 48, extcount: 6 },
			{ offset: 49, extcount: 6 },
			{ offset: 50, extcount: 6 },
			{ offset: 51, extcount: 6 },
			{ offset: 52, extcount: 6 },
			{ offset: 53, extcount: 6 },
			{ offset: 54, extcount: 6 },
			{ offset: 55, extcount: 6 }
		],
		MUXS: [
			{ mux: 'A', mcu: 'MCU_SAMD21' },
			{ mux: 'B', mcu: 'MCU_SAMD21' },
			{ mux: 'C', mcu: 'MCU_SAMD21' },
			{ mux: 'D', mcu: 'MCU_SAMD21' },
			{ mux: 'E', mcu: 'MCU_SAMD21' },
			{ mux: 'F', mcu: 'MCU_SAMD21' },
			{ mux: 'G', mcu: 'MCU_SAMD21' },
			{ mux: 'H', mcu: 'MCU_SAMD21' }
		],
		CONTROLS: [
			{ pin: 'ESTOP' },
			{ pin: 'SAFETY_DOOR' },
			{ pin: 'FHOLD' },
			{ pin: 'CS_RES' }
		],
		LIMITS: [
			{ pin: 'LIMIT_X', axis: '1,2,3,4,5,6' },
			{ pin: 'LIMIT_Y', axis: '2,3,4,5,6' },
			{ pin: 'LIMIT_Z', axis: '3,4,5,6' },
			{ pin: 'LIMIT_X2', axis: '1,2,3,4,5,6' },
			{ pin: 'LIMIT_Y2', axis: '2,3,4,5,6' },
			{ pin: 'LIMIT_Z2', axis: '3,4,5,6' },
			{ pin: 'LIMIT_A', axis: '4,5,6' },
			{ pin: 'LIMIT_B', axis: '5,6' },
			{ pin: 'LIMIT_C', axis: '6' },
		],
		TOOLS: [
			{ tool: 'TOOL1', toolcount: 1 },
			{ tool: 'TOOL2', toolcount: 2 },
			{ tool: 'TOOL3', toolcount: 3 },
			{ tool: 'TOOL4', toolcount: 4 },
			{ tool: 'TOOL5', toolcount: 5 },
			{ tool: 'TOOL6', toolcount: 6 },
			{ tool: 'TOOL7', toolcount: 7 },
			{ tool: 'TOOL8', toolcount: 8 },
			{ tool: 'TOOL8', toolcount: 9 },
			{ tool: 'TOOL9', toolcount: 10 },
			{ tool: 'TOOL10', toolcount: 11 },
			{ tool: 'TOOL11', toolcount: 12 },
			{ tool: 'TOOL12', toolcount: 13 },
			{ tool: 'TOOL13', toolcount: 14 },
			{ tool: 'TOOL14', toolcount: 15 },
			{ tool: 'TOOL15', toolcount: 16 }
		],
		ENCODER_LIST: [
			{ id: 'ENC0', enccount: 0 },
			{ id: 'ENC1', enccount: 1 },
			{ id: 'ENC2', enccount: 2 },
			{ id: 'ENC3', enccount: 3 },
			{ id: 'ENC4', enccount: 4 },
			{ id: 'ENC5', enccount: 5 },
			{ id: 'ENC6', enccount: 6 },
			{ id: 'ENC7', enccount: 7 }
		],
		STEP_ENCODERS: [
			{ id: 'STEP0_ENCODER' },
			{ id: 'STEP1_ENCODER' },
			{ id: 'STEP2_ENCODER' },
			{ id: 'STEP3_ENCODER' },
			{ id: 'STEP4_ENCODER' },
			{ id: 'STEP5_ENCODER' },
			{ id: 'STEP6_ENCODER' },
			{ id: 'STEP7_ENCODER' }
		],
		AXIS: [
			{ key: 1 },
			{ key: 2 },
			{ key: 3 },
			{ key: 4 },
			{ key: 5 },
			{ key: 6 }
		],
		DYNAMIC: {},

		TOOL_OPTIONS: [
			{ id: 'spindle_pwm', name: 'Spindle PWM' },
			{ id: 'spindle_besc', name: 'BESC Spindle' },
			{ id: 'spindle_relay', name: 'Spindle Relay' },
			{ id: 'laser_pwm', name: 'Laser PWM' },
			{ id: 'laser_ppi', name: 'Laser PPI' },
			{ id: 'vfd_modbus', name: 'VFD Modbus' },
			{ id: 'vfd_pwm', name: 'VFD PWM' },
			{ id: 'pen_servo', name: 'Pen Servo' },
			{ id: 'plasma_thc', name: 'Plasma THC' }
		],
		MODULES_OPTIONS: [
			{ id: 'g5', name: 'Linux CNC G5 and G5.1 and allows to make motions based on splines via control points' },
			{ id: 'g7_g8', name: 'Linux CNC G7/G8 to set radius mode for lathes' },
			{ id: 'g28_1_g30_1', name: 'Linux CNC G28.1/G30.1 to set homing coordinates to the current machine position' },
			{ id: 'g33', name: 'Linux CNC G33 and allows to make motions synched with the spindle' },
			{ id: 'm17_m18', name: 'Marlin M17-M18 and allows enable/disable stepper motors' },
			{ id: 'm42', name: 'Marlin M42 and allows to turn on and off any generic digital pin, PWM or servo pin' },
			{ id: 'm62_m65', name: 'LinuxCNC M62-M65 and allows to turn on and off any generic digital pin (synched or immediately)' },
			{ id: 'm66', name: 'LinuxCNC M66 and allows to wait on digital or analog input pin of the µCNC' },
			{ id: 'm67_m68', name: 'LinuxCNC M67-M68 and allows to turn on and off any analog pin (synched or immediately)' },
			{ id: 'm80_m81', name: 'Marlin M80-M81 and allows to turn on and off a pin controling the PSU' },
			{ id: 'i2c_lcd', name: 'Support for an I2C LCD that display the current machine position and limits state' },
			{ id: 'smoothie_clustering', name: 'Smoothieware S Cluster support' },
			{ id: 'i2c_eeprom', name: 'Adds support for external I2C EEPROMs to store settings' },
			{ id: 'spi_flash', name: 'Adds support for external SPI W25Qxxx NOR Flash to store settings' },
			{ id: 'graphic_display', name: 'Support for RepRap Full Graphic Display', lib_deps: 'olikraus/U8g2' },
			/*{ id: 'sd_card', name: 'Support for SD/MMC card via hardware/software SPI (DEPRECATED)' },*/
			{ id: 'stm32_sdio', name: 'Enables SDIO support for SD Card module. Requires SD Card module', requires: 'sd_card_v2' },
			{ id: 'sd_card_v2', name: 'Support for SD/MMC card via hardware/software SPI (v2 requires at least v1.9.0 to work)', condition: 'VERSION>010879' },
			{ id: 'bltouch', name: 'Support for BLTouch probe' },
			{ id: 'web_pendant', name: 'Adds an improved web pendant for WiFi capable devices. (requires at least v1.9.0 to work)', condition: 'VERSION>010879' },
			{ id: 'tmc_driver', name: 'Support for TMC drivers. (requires at least v1.8.7 to work)', condition: 'VERSION>010806' },
			{ id: 'tone_speaker', name: 'Plays sounds and tunes using a PWM output.' },
			{ id: 'mks_display', name: 'Adds support for MKS TS35-R display and similar ones.', condition: 'VERSION>019090', requires: 'touch_screen', lib_deps: 'lvgl/lvgl@^9.1.0', build_flags: '-DLV_CONF_PATH="${platformio.include_dir}/src/modules/mks_display/lv_conf.h"' },
			{ id: 'tft_display', name: 'Adds support for TFT displays like the ILI9341 and others. Uses lvgl_support to display a Win95 style menu', condition: 'VERSION>019090', requires: 'lvgl_support', lib_deps: 'lvgl/lvgl@^9.1.0', build_flags: '-DLV_CONF_PATH="${platformio.include_dir}/src/modules/lvgl_support/lv_conf.h"' },
			{ id: 'joystick', name: 'Adds support for an analog joystick to control up to 6 axis', condition: 'VERSION>019090' },
			// { id: 'joystick_v2', name: 'Newer version of the analog joystick to control up to 6 axis', condition: 'VERSION>011201' },
			{ id: 'grblhal_keypad', name: 'Adds support for GrblHAL keypad consoles', condition: 'VERSION>010800' },
			{ id: 'single_axis_homing', name: 'Adds single axis homing commands ($H<axis_letter> for example $HX)', condition: 'VERSION>010800' },
			// { id: 'lvgl_support', name: 'LVGL system menu emulating Win95 for the tft_display module.', condition: 'VERSION>019090', lib_deps: 'lvgl/lvgl@^9.1.0', build_flags: '-DLV_CONF_PATH="${platformio.include_dir}/src/modules/lvgl_support/lv_conf.h"' },
		],
		STEPPERS: [
			{id:'0'},
			{id:'1'},
			{id:'2'},
			{id:'3'},
			{id:'4'},
			{id:'5'},
			{id:'6'},
			{id:'7'}
		],
		TMCS: [
			{id:'2202', name:'2202'},
			{id:'2208', name:'2208'},
			{id:'2209', name:'2209'},
			{id:'2225', name:'2225'},
			{id:'2226', name:'2226'},
			{id:'2130', name:'2130'}
		],
		TMCS_COM: [
			{ id: 'TMC_UART', name: 'Software UART' },
			{ id: 'TMC_SPI', name: 'Software SPI' },
			{ id: 'TMC_ONEWIRE', name: 'Software ONEWIRE' },
			{ id: 'TMC_UART2_HW', name: 'Hardware UART2' },
			{ id: 'TMC_SPI_HW', name: 'Hardware SPI' },
		],
		LINACTS: [
			{ value: '1', name: 'LINACT0_IO_MASK', label: 'Linear actuator 0 (AXIS X) STEP IO outputs', axisnum: 0 },
			{ value: '2', name: 'LINACT1_IO_MASK', label: 'Linear actuator 1 (AXIS Y) STEP IO outputs', axisnum: 1 },
			{ value: '4', name: 'LINACT2_IO_MASK', label: 'Linear actuator 2 (AXIS Z) STEP IO outputs', axisnum: 2 },
			{ value: '8', name: 'LINACT3_IO_MASK', label: 'Linear actuator 3 (AXIS A) STEP IO outputs', axisnum: 3 },
			{ value: '16', name: 'LINACT4_IO_MASK', label: 'Linear actuator 4 (AXIS B) STEP IO outputs', axisnum: 4 },
			{ value: '32', name: 'LINACT5_IO_MASK', label: 'Linear actuator 5 (AXIS C) step IO outputs', axisnum: 5 }
		],
		LINACTS_LIMITS: [
			{ value: '1', name: 'LIMIT_X_IO_MASK', label: 'Limit X will stop which STEP IO output?', axisnum: 0, pin: 'LIMIT_X' },
			{ value: '2', name: 'LIMIT_Y_IO_MASK', label: 'Limit Y will stop which STEP IO output?', axisnum: 1, pin: 'LIMIT_Y' },
			{ value: '4', name: 'LIMIT_Z_IO_MASK', label: 'Limit Z will stop which STEP IO output?', axisnum: 2, pin: 'LIMIT_Z' },
			{ value: '8', name: 'LIMIT_A_IO_MASK', label: 'Limit A will stop which STEP IO output?', axisnum: 3, pin: 'LIMIT_A' },
			{ value: '16', name: 'LIMIT_B_IO_MASK', label: 'Limit B will stop which STEP IO output?', axisnum: 4, pin: 'LIMIT_B' },
			{ value: '32', name: 'LIMIT_C_IO_MASK', label: 'Limit C will stop which STEP IO output?', axisnum: 5, pin: 'LIMIT_C' },
			{ value: '1', name: 'LIMIT_X2_IO_MASK', label: 'Limit X2 will stop which STEP IO output?', axisnum: 3, pin: 'LIMIT_X2' },
			{ value: '2', name: 'LIMIT_Y2_IO_MASK', label: 'Limit Y2 will stop which STEP IO output?', axisnum: 4, pin: 'LIMIT_Y2' },
			{ value: '4', name: 'LIMIT_Z2_IO_MASK', label: 'Limit Z2 will stop which STEP IO output?', axisnum: 5, pin: 'LIMIT_Z2' }
		],
		STEP_IOS: [
			{ value: 1, name: 'STEP0', selected: false },
			{ value: 2, name: 'STEP1', selected: false },
			{ value: 4, name: 'STEP2', selected: false },
			{ value: 8, name: 'STEP3', selected: false },
			{ value: 16, name: 'STEP4', selected: false },
			{ value: 32, name: 'STEP5', selected: false },
			{ value: 64, name: 'STEP6', selected: false },
			{ value: 128, name: 'STEP7', selected: false }
		],
		MICROSTEPS: [
			1,
			2,
			4,
			8,
			16,
			32
		],
		TOOLCHAINS: [
			{ id: 'pio', value: 'VSCode / PlatformIO' },
			{ id: 'other', value: 'Arduino IDE or makefiles' }
		]
	},
	app_pins: []
};

function updateAppPins() {
	var pins = window.app_vars.app_options.UCNCPINS.map(x => x.pin);
	pins.forEach((pin) => {
		if (window.app_vars.app_state[pin + '_BIT'] || (window.app_vars.app_state[pin + '_IO_OFFSET'])) {
			switch (window.app_vars.app_state) {
				case 'MCU_ESP8266':
				case 'MCU_ESP32':
				case 'MCU_ESP32C3':
				case 'MCU_ESP32S3':
				case 'MCU_RP2040':
				case 'MCU_RP2350':
					window.app_vars.app_pins.push(pin);
					break;
				default:
					if (window.app_vars.app_state[pin + '_BIT'] && window.app_vars.app_state[pin + '_PORT']) {
						window.app_vars.app_pins.push(pin);
					}
					else if (window.app_vars.app_state[pin + '_IO_OFFSET']) {
						window.app_vars.app_pins.push(pin);
					}
					else {
						window.app_vars.app_pins = window.app_vars.app_pins.filter((i) => { i != pin; });
					}
					break;
			}
		}
		else {
			window.app_vars.app_pins = window.app_vars.app_pins.filter((i) => { i != pin; });
		}
	});
}